# image:
#   file: .gitpod.Dockerfile

tasks:
  - name: Build
    init: cargo build
  - name: Install trunk
    init: cargo install trunk wasm-bindgen-cli

github:
  prebuilds:
    branches: true
    pullRequestsFromForks: true
    addLabel: prebuilt-in-gitpod
